import React, { useState, useEffect } from 'react';
import axios from 'axios';

const ProjectForm = () => {
    const [title, setTitle] = useState('');
    const [content, setContent] = useState('');
    const [generatedBy, setGeneratedBy] = useState('');
    const [project, setProject] = useState('');
    const [priority, setPriority] = useState('');
    const [users, setUsers] = useState([]);
    const [projects, setProjects] = useState([]); // Initialize as an empty array

    useEffect(() => {
        const fetchOptions = async () => {
            try {
                const [usersRes, projectsRes] = await Promise.all([
                    axios.get('/users'),
                    axios.get('/api/projects')
                ]);

                console.log('Projects Response:', projectsRes.data); // Log the response

                setUsers(usersRes.data);
                setProjects(Array.isArray(projectsRes.data) ? projectsRes.data : []); // Ensure projects is an array
            } catch (err) {
                console.error(err);
                setProjects([]); // Set projects to an empty array on error
            }
        };
        fetchOptions();
    }, []);

    const handleSubmit = async (e) => {
        e.preventDefault();
        try {
            const response = await axios.post('/api/projects', {
                title,
                content,
                generatedBy,
                project,
                priority,
            });
            console.log('Project added:', response.data);
        } catch (err) {
            console.error('Error adding project:', err);
        }
    };

    return (
        <form onSubmit={handleSubmit}>
            <div>
                <label htmlFor="title">Title</label>
                <input
                    id="title"
                    type="text"
                    value={title}
                    onChange={(e) => setTitle(e.target.value)}
                />
            </div>
            <div>
                <label htmlFor="content">Content</label>
                <textarea
                    id="content"
                    value={content}
                    onChange={(e) => setContent(e.target.value)}
                />
            </div>
            <div>
                <label htmlFor="generatedBy">Generated By</label>
                <select
                    id="generatedBy"
                    value={generatedBy}
                    onChange={(e) => setGeneratedBy(e.target.value)}
                >
                    <option value="">Select User</option>
                    {users.map((user) => (
                        <option key={user._id} value={user._id}>
                            {user.name}
                        </option>
                    ))}
                </select>
            </div>
            <div>
                <label htmlFor="project">Project</label>
                <select
                    id="project"
                    value={project}
                    onChange={(e) => setProject(e.target.value)}
                >
                    <option value="">Select Project</option>
                    {projects.map((project) => (
                        <option key={project._id} value={project._id}>
                            {project.title}
                        </option>
                    ))}
                </select>
            </div>
            <div>
                <label htmlFor="priority">Priority</label>
                <input
                    id="priority"
                    type="text"
                    value={priority}
                    onChange={(e) => setPriority(e.target.value)}
                />
            </div>
            <button type="submit">Add Project</button>
        </form>
    );
};

export default ProjectForm;
